version: "3.8"
services:

  redis:
    build:
      context: ./redis
    volumes:
      - ./redis/data/:/data
    environment:
      - REDIS_REPLICATION_MODE=master
  api:
    build:
      context: ./api
    volumes:
      - ./api/data/:/app/data/
    ports:
      - 8080
    labels:
      - "traefik.http.routers.lb.rule=PathPrefix(`/`)"
      - "traefik.http.routers.lb.entrypoints=api"
      - "traefik.enable=true"
    deploy:
      mode: replicated
      replicas: 3
  lb:
    build:
      context: ./traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.api.address=:80"
      - "--accesslog=true"
      - "--log.level=WARN"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
